# ====== SERVER =====
server.port=${PORT:8080}

# ====== GENERAL SPRING CONFIGURATION =====
spring.application.name=uploader
spring.config.import=optional:file:.env[.properties]

# ====== MULTIPART CONFIGURATION =====
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=tmp

# ====== DOCUMENTATION CONFIGURATION =====
scalar.enabled=true
scalar.path=/docs
scalar.dark-mode=true
scalar.theme=blue_planet
scalar.hide-models=true
scalar.hide-client-button=true
scalar.page-title=Uploader API documentation
scalar.default-http-client.target-key=shell
scalar.default-http-client.client-key=curl
